<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<<<<<<< HEAD
<testsuite hostname="DESKTOP-Q6UCOPF" failures="0" tests="1" name="TestCases.com_testcase_brokenlink" time="197.951" errors="0" timestamp="2025-04-12T08:29:46 IST" skipped="0">
  <testcase classname="TestCases.com_testcase_brokenlink" name="enterContactInformation" time="197.951"/>
=======
<testsuite hostname="DESKTOP-Q8QMA40" failures="0" tests="1" name="TestCases.com_testcase_brokenlink" time="0.068" errors="1" timestamp="2025-04-13T09:00:57 IST" skipped="0">
  <testcase classname="TestCases.com_testcase_brokenlink" name="enterContactInformation2" time="0.068">
    <error message="Cannot invoke &quot;org.openqa.selenium.WebDriver.findElements(org.openqa.selenium.By)&quot; because &quot;driverIntializer.driverIntializer.driver&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.WebDriver.findElements(org.openqa.selenium.By)" because "driverIntializer.driverIntializer.driver" is null
at TestCases.com_testcase_brokenlink.enterContactInformation2(com_testcase_brokenlink.java:109)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
    </error>
  </testcase> <!-- enterContactInformation2 -->
>>>>>>> 4e8e99c059bd628c912aa0ceb8b0f31087aca5d0
</testsuite> <!-- TestCases.com_testcase_brokenlink -->
